[package]
name = "fusion-cache-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
moka = { version = "0.12.10", features = ["future"] }
tokio = { version = "1.44.1", features = ["full"] }
chrono = "0.4.40"
futures = "0.3.31"
async-trait = "0.1.88"
